from testsetclass import TestsetClass
class BH76_full(TestsetClass):
    """
    A class to store molecular data and corresponding calculations for BH76 dataset.

    Attributes
    ----------
    molecules : list[str]
        List of molecule identifiers used in test calculations.

    exp_values : dict[str, float]
        Dictionary mapping test identifiers to their expected (experimental) values.

    testset_calculations : dict[str, str]
        Dictionary describing molecular calculations in symbolic format, 
        defining the reaction or calculation for each test identifier.

    """
    def __init__(self):
        self.molecules = ['h', 'n2o', 'n2ohts', 'oh', 'n2',
                                    'hf', 'hfhts', 'hcl', 'hclhts',
                                    'ch3f', 'hfch3ts', 'ch3', 'f2', 'hf2ts',
                                    'f', 'clf', 'ch3fclts', 'cl', 'f-',
                                    'fch3fts', 'fch3fcomp', 'cl-', 'ch3cl',
                                    'clch3clts', 'clch3clcomp', 'fch3clts',
                                    'fch3clcomp1', 'fch3clcomp2', 'oh-', 'hoch3fts',
                                    'ch3oh', 'hoch3fcomp2', 'hoch3fcomp1', 'hn2ts',
                                    'n2h', 'co', 'hcots', 'hco', 'c2h4',
                                    'c2h5ts', 'c2h5', 'c3h7ts', 'c3h7',
                                    'hcn', 'hcnts', 'hnc', 'h2', 'h2o',
                                    'ch4', 'nh3', 'nh2', 'c2h6', 'o',
                                    'ph3', 'ph2', 'h2s', 'sh', 'nh',
                                    'clhhts', 'hohhts', 'ch3h2ts',
                                    'ch3hohts', 'hhhts', 'nh2hohts',
                                    'clhch3ts', 'c2h5hohts', 'fhhts', 'ch3hots',
                                    'ph2hhts', 'hohts', 'hshhts', 'ohcl',
                                    'ch3hnhts', 'c2h5hnhts', 'c2h5hnh2ts',
                                    'ch3hnh2ts', 'c5h8ts','c5h8'
                                    ]
        self.exp_values = {'1': 17.7, '2': 82.6, '3': 42.1, '4': 42.1, '5': 17.8,
                           '6': 17.8, '7': 30.5, '8': 56.9, '9': 1.5, '10': 104.8,
                           '11': 7.1, '12': 59.8, '13': -0.6, '14': -0.6, '15': 13.4,
                           '16': 13.4, '17': 2.5, '18': 2.5, '19': 13.5, '20': 13.5,
                           '21': -12.3, '22': 19.8, '23': 3.5, '24': 29.6, '25': -2.7,
                           '26': 17.6, '27': 11.0, '28': 47.7, '29': 14.6, '30': 10.9,
                           '31': 3.2, '32': 22.8, '33': 2.0, '34': 42.0, '35': 6.4,
                           '36': 33.0, '37': 48.1, '38': 33.0, '39': 6.1, '40': 8.0,
                           '41': 5.2, '42': 21.6, '43': 11.9, '44': 15.0, '45': 6.3,
                           '46': 19.5, '47': 9.7, '48': 9.7, '49': 3.4, '50': 13.7,
                           '51': 1.8, '52': 6.8, '53': 3.5, '54': 20.4, '55': 1.6,
                           '56': 33.8, '57': 14.4, '58': 8.9, '59': 2.9, '60': 24.7,
                           '61': 10.9, '62': 13.2, '63': 3.9, '64': 17.2, '65': 10.4,
                           '66': 9.9, '67': 8.9, '68': 22.0, '69': 9.8, '70': 19.4,
                           '71': 11.3, '72': 17.8, '73': 13.9, '74': 16.9, 
                           '75': 39.7,
                           '76': 39.7
                           }

        self.testset_calculations = {'1': "-['h']            - ['n2o']      + ['n2ohts']",
                                     '2': "-['oh']           - ['n2']       + ['n2ohts']",
                                     '3': "-['h']            - ['hf']       + ['hfhts']",
                                     '4': "-['hf']           - ['h']        + ['hfhts']",
                                     '5': "-['h']            - ['hcl']      + ['hclhts']",
                                     '6': "-['hcl']          - ['h']        + ['hclhts']",
                                     '7': "-['h']            - ['ch3f']     + ['hfch3ts']",
                                     '8': "-['hf']           - ['ch3']      + ['hfch3ts']",
                                     '9': "-['h']            - ['f2']       + ['hf2ts']",
                                     '10': "-['hf']           - ['f']        + ['hf2ts']",
                                     '11': "-['ch3']          - ['clf']      + ['ch3fclts']",
                                     '12': "-['ch3f']         - ['cl']       + ['ch3fclts']",
                                     '13': "-['f-']           - ['ch3f']     + ['fch3fts']",
                                     '14': "-['ch3f']         - ['f-']       + ['fch3fts']",
                                     '15': "-['fch3fcomp']    + ['fch3fts']",
                                     '16': "-['fch3fcomp']    + ['fch3fts']",
                                     '17': "-['cl-']          - ['ch3cl']    + ['clch3clts']",
                                     '18': "-['ch3cl']        - ['cl-']      + ['clch3clts']",
                                     '19': "-['clch3clcomp']  + ['clch3clts']",
                                     '20': "-['clch3clcomp']  + ['clch3clts']",
                                     '21': "-['f-']           - ['ch3cl']    + ['fch3clts']",
                                     '22': "-['cl-']          - ['ch3f']     + ['fch3clts']",
                                     '23': "-['fch3clcomp1']  + ['fch3clts']",
                                     '24': "-['fch3clcomp2']  + ['fch3clts']",
                                     '25': "-['oh-']          - ['ch3f']     + ['hoch3fts']",
                                     '26': "-['ch3oh']        - ['f-']       + ['hoch3fts']",
                                     '27': "-['hoch3fcomp2']  + ['hoch3fts']",
                                     '28': "-['hoch3fcomp1']  + ['hoch3fts']",
                                     '29': "-['h']            - ['n2']       + ['hn2ts']",
                                     '30': "-['n2h']          + ['hn2ts']",
                                     '31': "-['h']            - ['co']       + ['hcots']",
                                     '32': "-['hco']          + ['hcots']",
                                     '33': "-['h']            - ['c2h4']     + ['c2h5ts']",
                                     '34': "-['c2h5']         + ['c2h5ts']",
                                     '35': "-['ch3']          - ['c2h4']     + ['c3h7ts']",
                                     '36': "-['c3h7']         + ['c3h7ts']",
                                     '37': "-['hcn']          + ['hcnts']",
                                     '38': "-['hnc']          + ['hcnts']",
                                     '39': "-['h']            - ['hcl']      + ['clhhts']",
                                     '40': "-['h2']           - ['cl']+['clhhts']",
                                     '41': "-['oh']           - ['h2']+['hohhts']",
                                     '42': "-['h2o']          - ['h']+['hohhts']",
                                     '43': "-['ch3']          - ['h2']+['ch3h2ts']",
                                     '44': "-['ch4']          - ['h']+['ch3h2ts']",
                                     '45': "-['oh']           - ['ch4']+['ch3hohts']",
                                     '46': "-['h2o']          - ['ch3']+['ch3hohts']",
                                     '47': "-['h']            - ['h2']+['hhhts']",
                                     '48': "-['h']            - ['h2']+['hhhts']",
                                     '49': "-['oh']           - ['nh3']+['nh2hohts']",
                                     '50': "-['h2o']          - ['nh2']+['nh2hohts']",
                                     '51': "-['hcl']          - ['ch3']+['clhch3ts']",
                                     '52': "-['cl']           - ['ch4']+['clhch3ts']",
                                     '53': "-['oh']           - ['c2h6']+['c2h5hohts']",
                                     '54': "-['h2o']          - ['c2h5']+['c2h5hohts']",
                                     '55': "-['f']            - ['h2']+['fhhts']",
                                     '56': "-['hf']           - ['h']+['fhhts']",
                                     '57': "-['o']            - ['ch4']+['ch3hots']",
                                     '58': "-['oh']           - ['ch3']+['ch3hots']",
                                     '59': "-['h']            - ['ph3']+['ph2hhts']",
                                     '60': "-['h2']           - ['ph2']+['ph2hhts']",
                                     '61': "-['h']            - ['oh']+['hohts']",
                                     '62': "-['h2']           - ['o']+['hohts']",
                                     '63': "-['h']            - ['h2s']+['hshhts']",
                                     '64': "-['h2']           - ['sh']+['hshhts']",
                                     '65': "-['o']            - ['hcl']+['ohcl']",
                                     '66': "-['oh']           - ['cl']+['ohcl']",
                                     '67': "-['nh2']          - ['ch3']+['ch3hnhts']",
                                     '68': "-['nh']           - ['ch4']+['ch3hnhts']",
                                     '69': "-['nh2']          - ['c2h5']+['c2h5hnhts']",
                                     '70': "-['nh']           - ['c2h6']+['c2h5hnhts']",
                                     '71': "-['c2h6']         - ['nh2']+['c2h5hnh2ts']",
                                     '72': "-['c2h5']         - ['nh3']+['c2h5hnh2ts']",
                                     '73': "-['nh2']          - ['ch4']+['ch3hnh2ts']",
                                     '74': "-['nh3']          - ['ch3']+['ch3hnh2ts']",
                                     '75': "-['c5h8']         + ['c5h8ts']",
                                     '76': "-['c5h8']         + ['c5h8ts']"
                                   }

        self.charges = {"c2h4": 0.000,
                        "c2h5": 0.000,
                        "c2h5hnh2ts": -0.000,
                        "c2h5hnhts": -0.000,
                        "c2h5hohts": 0.000,
                        "c2h5ts": 0.000,
                        "c2h6": 0.000,
                        "c3h7": 0.000,
                        "c3h7ts": 0.000,
                        "c5h8": 0.000,
                        "c5h8ts": -0.000,
                        "ch3": 0.000,
                        "ch3cl": -0.000,
                        "ch3f": 0.000,
                        "ch3fclts": -0.000,
                        "ch3h2ts": 0.000,
                        "ch3hnh2ts": 0.000,
                        "ch3hnhts": 0.000,
                        "ch3hohts": 0.000,
                        "ch3hots": 0.000,
                        "ch3oh": -0.000,
                        "ch4": -0.000,
                        "cl-": -1.000,
                        "cl": -0.000,
                        "clch3clcomp": -1.000,
                        "clch3clts": -1.000,
                        "clf": -0.000,
                        "clhch3ts": -0.000,
                        "clhhts": -0.000,
                        "co": 0.000,
                        "f-": -1.000,
                        "f": 0.000,
                        "f2": 0.000,
                        "fch3clcomp1": -1.000,
                        "fch3clcomp2": -1.000,
                        "fch3clts": -1.000,
                        "fch3fcomp": -1.000,
                        "fch3fts": -1.000,
                        "fhhts": -0.000,
                        "h": 0.000,
                        "h2": 0.000,
                        "h2o": -0.000,
                        "h2s": -0.000,
                        "hcl": -0.000,
                        "hclhts": -0.000,
                        "hcn": -0.000,
                        "hcnts": 0.000,
                        "hco": 0.000,
                        "hcots": 0.000,
                        "hf": -0.000,
                        "hf2ts": 0.000,
                        "hfch3ts": 0.000,
                        "hfhts": -0.000,
                        "hhhts": -0.000,
                        "hn2ts": 0.000,
                        "hnc": 0.000,
                        "hoch3fcomp1": -1.000,
                        "hoch3fcomp2": -1.000,
                        "hoch3fts": -1.000,
                        "hohhts": 0.000,
                        "hohts": 0.000,
                        "hshhts": -0.000,
                        "n2": 0.000,
                        "n2h": 0.000,
                        "n2o": -0.000,
                        "n2ohts": -0.000,
                        "nh": 0.000,
                        "nh2": 0.000,
                        "nh2hohts": 0.000,
                        "nh3": -0.000,
                        "o": -0.000,
                        "oh-": -1.000,
                        "oh": 0.000,
                        "ohcl": -0.000,
                        "ph2": -0.000,
                        "ph2hhts": -0.000,
                        "ph3": -0.000,
                        "sh": -0.000}
