from testsetclass import TestsetClass
class W417(TestsetClass):
    """
    A class to store molecular data and corresponding calculations for W417 dataset.

    Attributes
    ----------
    molecules : list[str]
        List of molecule identifiers used in test calculations.

    exp_values : dict[str, float]
        Dictionary mapping test identifiers to their expected (experimental) values.

    testset_calculations : dict[str, str]
        Dictionary describing molecular calculations in symbolic format, 
        defining the reaction or calculation for each test identifier.

    """
    def __init__(self):
        self.molecules = ['cyclobutene', 't-butadiene', 'cyclobutane', 'n-pentane', 'benzene', 'acetic', 'hclo4', 
                           'c2f6', 'c2cl6', 'n2o4', 'cloocl', 'clo3', 'hoclo', 'pf5', 'sf6', 'oxadiazole', 'dioxetan2one',
                           'dioxetane', 'dithiotane', 'borole', 'c2cl4', 'c2f4', 'cis-c2f2cl2', 'trans-c2f2cl2', 
                           'cyclopentadiene', 'formic-anhydride', 'furan', 'oxetane', 'pyrrole', 'silole', 'thiophene', 
                           'beta-lactim', 'clf5', 'clf3', 'pf3', 'hoclo2', 'h2no', 'nh2oh', 'cyclopropane', 'cyclopropene', 
                           'ch3ph2', 'nh2f', 'cclh3', 'clno', 'tetrahedrane', 'n-butane', 'c2cl2', 'c2clh3', 'c2clh5', 'c2clh', 
                           'ccl2h2', 'ccl2o', 'ccl3h', 'ccl4', 'cf2cl2', 'fno', 'ch2clf', 'chf3', 'clcof', 'formamide', 'cyclobutadiene', 
                           'allyl', 'cyclopropyl', 'h2ccn', 'oxirene', 'oxirane', 'dioxirane', 'ketene', 'acetaldehyde', 'formic', 
                           'methanol', 'ethanol', 'glyoxal', 't-hcoh', 'c-hcoh', 'hcnh', 'hocn', 'honc', 'hnco', 'hcno', 'c-n2h2', 
                           'hnnn', 'hnc', 't-hono', 'c-hono', 'nh2cl', 't-hooo', 'c-hooo', 'ch3f', 'ch2f2', 'cf4', 'sih3f', 'sif4', 
                           'c2h3f', 'c2h5f', 'fccf', 'hccf', 'hcof', 'f2co', 'ch2-sing', 'propane', 'propene', 'propyne', 'allene', 
                           'b2h6', 'bhf2', 'bf3', 'c2h6', 'h2cn', 'nccn', 'ch2nh2', 'ch3nh', 'ch3nh2', 'cf2', 'n2h', 't-n2h2', 'n2h4',
                           'fo2', 'foof', 'alf3', 'si2h6', 'p4', 'so2', 'so3', 'ocs', 'cs2', 's2o', 's3', 's4-c2v', 'ccl2', 'alcl3', 
                           'clcn', 'oclo', 'cloo', 'cl2o', 'bn3pi', 'cf', 'ch2c', 'ch2ch', 'c2h4', 'ch2nh', 'hco', 'h2co', 'co2', 
                           'hno', 'no2', 'n2o', 'o3', 'hoo', 'hooh', 'f2o', 'hocl', 'ssh', 'b2', 'bh', 'bh3', 'bn', 'bf', 'nh', 
                           'nh2', 'hcn', 'hof', 'alh', 'alh3', 'alf', 'alcl', 'sih', 'sih4', 'sio', 'sif', 'cs', 'h2', 'oh', 'hf', 
                           'h2o', 'ch', 'ch2-trip', 'ch3', 'ch4', 'cch', 'c2h2', 'nh3', 'c2', 'n2', 'co', 'cn', 'no', 'o2', 'of', 
                           'f2', 'ph3', 'hs', 'h2s', 'hcl', 'so', 'clo', 'clf', 'p2', 's2', 'cl2','al','s','si','b','h','n','o','f','c','cl','p']
        self.exp_values = {
                            'cyclobutene': 1001.542,
                            't-butadiene': 1013.069,
                            'cyclobutane': 1150.396,
                            'n-pentane': 1597.309,
                            'benzene': 1368.8,
                            'acetic': 803.97,
                            'hclo4': 335.412,
                            'c2f6': 791.944,
                            'c2cl6': 561.305,
                            'n2o4': 471.67,
                            'cloocl': 149.125,
                            'clo3': 169.836,
                            'hoclo': 204.289,
                            'pf5': 561.565,
                            'sf6': 485.425,
                            'oxadiazole': 706.069,
                            'dioxetan2one': 753.117,
                            'dioxetane': 750.002,
                            'dithiotane': 684.391,
                            'borole': 1057.669,
                            'c2cl4': 471.76,
                            'c2f4': 590.066,
                            'cis-c2f2cl2': 529.019,
                            'trans-c2f2cl2': 529.39,
                            'cyclopentadiene': 1181.901,
                            'formic-anhydride': 757.007,
                            'furan': 995.125,
                            'oxetane': 948.139,
                            'pyrrole': 1072.798,
                            'silole': 1100.905,
                            'thiophene': 964.987,
                            'beta-lactim': 993.865,
                            'clf5': 186.794,
                            'clf3': 128.547,
                            'pf3': 365.599,
                            'hoclo2': 273.177,
                            'h2no': 274.97,
                            'nh2oh': 359.723,
                            'cyclopropane': 853.968,
                            'cyclopropene': 681.94,
                            'ch3ph2': 539.303,
                            'nh2f': 256.47,
                            'cclh3': 396.046,
                            'clno': 191.958,
                            'tetrahedrane': 793.489,
                            'n-butane': 1302.63,
                            'c2cl2': 350.586,
                            'c2clh3': 544.317,
                            'c2clh5': 692.913,
                            'c2clh': 378.516,
                            'ccl2h2': 371.701,
                            'ccl2o': 347.085,
                            'ccl3h': 345.416,
                            'ccl4': 315.419,
                            'cf2cl2': 392.237,
                            'fno': 215.427,
                            'ch2clf': 402.838,
                            'chf3': 459.564,
                            'clcof': 383.378,
                            'formamide': 568.15,
                            'cyclobutadiene': 820.838,
                            'allyl': 766.855,
                            'cyclopropyl': 737.718,
                            'h2ccn': 512.654,
                            'oxirene': 456.03,
                            'oxirane': 651.49,
                            'dioxirane': 410.01,
                            'ketene': 533.44,
                            'acetaldehyde': 677.85,
                            'formic': 501.87,
                            'methanol': 513.47,
                            'ethanol': 811.2,
                            'glyoxal': 635.05,
                            't-hcoh': 322.46,
                            'c-hcoh': 317.64,
                            'hcnh': 336.21,
                            'hocn': 410.02,
                            'honc': 350.11,
                            'hnco': 434.68,
                            'hcno': 364.91,
                            'c-n2h2': 291.08,
                            'hnnn': 331.72,
                            'hnc': 298.18,
                            't-hono': 312.61,
                            'c-hono': 312.17,
                            'nh2cl': 248.04,
                            't-hooo': 233.27,
                            'c-hooo': 233.07,
                            'ch3f': 422.96,
                            'ch2f2': 437.935,
                            'cf4': 478.74,
                            'sih3f': 382.74,
                            'sif4': 577.76,
                            'c2h3f': 573.87,
                            'c2h5f': 721.48,
                            'fccf': 386.06,
                            'hccf': 398.45,
                            'hcof': 403.72,
                            'f2co': 420.61,
                            'ch2-sing': 181.44,
                            'propane': 1007.89,
                            'propene': 861.55,
                            'propyne': 705.57,
                            'allene': 704.07,
                            'b2h6': 607.02,
                            'bhf2': 410.96,
                            'bf3': 470.96,
                            'c2h6': 713.04,
                            'h2cn': 343.71,
                            'nccn': 501.96,
                            'ch2nh2': 482.24,
                            'ch3nh': 474.6,
                            'ch3nh2': 582.26,
                            'cf2': 258.77,
                            'n2h': 224.82,
                            't-n2h2': 296.49,
                            'n2h4': 438.24,
                            'fo2': 134.69,
                            'foof': 152.34,
                            'alf3': 430.96,
                            'si2h6': 535.88,
                            'p4': 290.57,
                            'so2': 260.58,
                            'so3': 346.89,
                            'ocs': 335.73,
                            'cs2': 280.76,
                            's2o': 208.75,
                            's3': 168.35,
                            's4-c2v': 234.33,
                            'ccl2': 177.32,
                            'alcl3': 312.64,
                            'clcn': 285.42,
                            'oclo': 128.09,
                            'cloo': 126.34,
                            'cl2o': 101.43,
                            'bn3pi': 105.81,
                            'cf': 132.71,
                            'ch2c': 359.92,
                            'ch2ch': 446.08,
                            'c2h4': 564.1,
                            'ch2nh': 439.45,
                            'hco': 279.43,
                            'h2co': 374.65,
                            'co2': 390.14,
                            'hno': 205.9,
                            'no2': 227.87,
                            'n2o': 270.85,
                            'o3': 147.43,
                            'hoo': 175.54,
                            'hooh': 269.08,
                            'f2o': 93.78,
                            'hocl': 166.23,
                            'ssh': 165.14,
                            'b2': 67.47,
                            'bh': 84.98,
                            'bh3': 281.28,
                            'bn': 105.24,
                            'bf': 182.53,
                            'nh': 83.09,
                            'nh2': 182.58,
                            'hcn': 313.42,
                            'hof': 158.66,
                            'alh': 73.58,
                            'alh3': 213.17,
                            'alf': 163.79,
                            'alcl': 122.62,
                            'sih': 73.93,
                            'sih4': 324.95,
                            'sio': 193.04,
                            'sif': 142.72,
                            'cs': 172.21,
                            'h2': 109.5,
                            'oh': 107.2,
                            'hf': 141.64,
                            'h2o': 232.98,
                            'ch': 84.22,
                            'ch2-trip': 190.74,
                            'ch3': 307.87,
                            'ch4': 420.44,
                            'cch': 266.17,
                            'c2h2': 405.54,
                            'nh3': 298.01,
                            'c2': 147.03,
                            'n2': 228.48,
                            'co': 259.73,
                            'cn': 181.36,
                            'no': 152.75,
                            'o2': 120.82,
                            'of': 53.07,
                            'f2': 39.05,
                            'ph3': 242.27,
                            'hs': 87.73,
                            'h2s': 183.91,
                            'hcl': 107.49,
                            'so': 126.47,
                            'clo': 65.44,
                            'clf': 62.8,
                            'p2': 117.61,
                            's2': 104.25,
                            'cl2': 59.75}
      
        self.testset_calculations = {
                                    'hoclo2': " -['hoclo2'] + 1*['cl'] + 1*['h'] + 3*['o']",
                                    'acetaldehyde': " -['acetaldehyde'] + 4*['h'] + 2*['c'] + 1*['o']",
                                    'acetic': " -['acetic'] + 4*['h'] + 2*['c'] + 2*['o']",
                                    'alcl3': " -['alcl3'] + 1*['al'] + 3*['cl']",
                                    'alcl': " -['alcl'] + 1*['al'] + 1*['cl']",
                                    'alf3': " -['alf3'] + 1*['al'] + 3*['f']",
                                    'alf': " -['alf'] + 1*['al'] + 1*['f']",
                                    'alh3': " -['alh3'] + 1*['al'] + 3*['h']",
                                    'alh': " -['alh'] + 1*['al'] + 1*['h']",
                                    'allene': " -['allene'] + 4*['h'] + 3*['c']",
                                    'allyl': " -['allyl'] + 5*['h'] + 3*['c']",
                                    'b2': " -['b2'] + 2*['b']",
                                    'b2h6': " -['b2h6'] + 6*['h'] + 2*['b']",
                                    'benzene': " -['benzene'] + 6*['h'] + 6*['c']",
                                    'beta-lactim': " -['beta-lactim'] + 1*['n'] + 5*['h'] + 3*['c'] + 1*['o']",
                                    'bf3': " -['bf3'] + 3*['f'] + 1*['b']",
                                    'bf': " -['bf'] + 1*['f'] + 1*['b']",
                                    'bh3': " -['bh3'] + 3*['h'] + 1*['b']",
                                    'bh': " -['bh'] + 1*['h'] + 1*['b']",
                                    'bhf2': " -['bhf2'] + 2*['f'] + 1*['h'] + 1*['b']",
                                    'bn3pi': " -['bn3pi'] + 1*['n'] + 1*['b']",
                                    'bn': " -['bn'] + 1*['n'] + 1*['b']",
                                    'borole': " -['borole'] + 1*['b'] + 5*['h'] + 4*['c']",
                                    'c2cl2': " -['c2cl2'] + 2*['cl'] + 2*['c']",
                                    'c2cl4': " -['c2cl4'] + 4*['cl'] + 2*['c']",
                                    'c2cl6': " -['c2cl6'] + 6*['cl'] + 2*['c']",
                                    'c2clh3': " -['c2clh3'] + 1*['cl'] + 3*['h'] + 2*['c']",
                                    'c2clh5': " -['c2clh5'] + 1*['cl'] + 5*['h'] + 2*['c']",
                                    'c2clh': " -['c2clh'] + 1*['cl'] + 1*['h'] + 2*['c']",
                                    'c2': " -['c2'] + 2*['c']",
                                    'c2f4': " -['c2f4'] + 4*['f'] + 2*['c']",
                                    'c2f6': " -['c2f6'] + 6*['f'] + 2*['c']",
                                    'c2h2': " -['c2h2'] + 2*['h'] + 2*['c']",
                                    'c2h3f': " -['c2h3f'] + 1*['f'] + 3*['h'] + 2*['c']",
                                    'c2h4': " -['c2h4'] + 4*['h'] + 2*['c']",
                                    'c2h5f': " -['c2h5f'] + 5*['h'] + 1*['f'] + 2*['c']",
                                    'c2h6': " -['c2h6'] + 6*['h'] + 2*['c']",
                                    'cch': " -['cch'] + 1*['h'] + 2*['c']",
                                    'ccl2': " -['ccl2'] + 2*['cl'] + 1*['c']",
                                    'ccl2h2': " -['ccl2h2'] + 2*['cl'] + 2*['h'] + 1*['c']",
                                    'ccl2o': " -['ccl2o'] + 2*['cl'] + 1*['c'] + 1*['o']",
                                    'ccl3h': " -['ccl3h'] + 3*['cl'] + 1*['h'] + 1*['c']",
                                    'ccl4': " -['ccl4'] + 4*['cl'] + 1*['c']",
                                    'cclh3': " -['cclh3'] + 1*['cl'] + 3*['h'] + 1*['c']",
                                    'cf2cl2': " -['cf2cl2'] + 2*['cl'] + 2*['f'] + 1*['c']",
                                    'cf2': " -['cf2'] + 2*['f'] + 1*['c']",
                                    'cf4': " -['cf4'] + 4*['f'] + 1*['c']",
                                    'cf': " -['cf'] + 1*['f'] + 1*['c']",
                                    'ch2c': " -['ch2c'] + 2*['h'] + 2*['c']",
                                    'ch2ch': " -['ch2ch'] + 3*['h'] + 2*['c']",
                                    'ch2clf': " -['ch2clf'] + 2*['h'] + 1*['cl'] + 1*['f'] + 1*['c']",
                                    'ch2f2': " -['ch2f2'] + 2*['f'] + 2*['h'] + 1*['c']",
                                    'ch2nh2': " -['ch2nh2'] + 1*['n'] + 4*['h'] + 1*['c']",
                                    'ch2nh': " -['ch2nh'] + 3*['h'] + 1*['n'] + 1*['c']",
                                    'ch2-sing': " -['ch2-sing'] + 2*['h'] + 1*['c']",
                                    'ch2-trip': " -['ch2-trip'] + 2*['h'] + 1*['c']",
                                    'ch3': " -['ch3'] + 3*['h'] + 1*['c']",
                                    'ch3f': " -['ch3f'] + 3*['h'] + 1*['f'] + 1*['c']",
                                    'ch3nh2': " -['ch3nh2'] + 5*['h'] + 1*['n'] + 1*['c']",
                                    'ch3nh': " -['ch3nh'] + 1*['n'] + 4*['h'] + 1*['c']",
                                    'ch3ph2': " -['ch3ph2'] + 5*['h'] + 1*['c'] + 1*['p']",
                                    'ch4': " -['ch4'] + 4*['h'] + 1*['c']",
                                    'c-hcoh': " -['c-hcoh'] + 2*['h'] + 1*['c'] + 1*['o']",
                                    'ch': " -['ch'] + 1*['h'] + 1*['c']",
                                    'chf3': " -['chf3'] + 3*['f'] + 1*['h'] + 1*['c']",
                                    'c-hono': " -['c-hono'] + 1*['h'] + 1*['n'] + 2*['o']",
                                    'c-hooo': " -['c-hooo'] + 1*['h'] + 3*['o']",
                                    'cis-c2f2cl2': " -['cis-c2f2cl2'] + 2*['cl'] + 2*['f'] + 2*['c']",
                                    'cl2': " -['cl2'] + 2*['cl']",
                                    'cl2o': " -['cl2o'] + 2*['cl'] + 1*['o']",
                                    'clcn': " -['clcn'] + 1*['cl'] + 1*['n'] + 1*['c']",
                                    'clcof': " -['clcof'] + 1*['cl'] + 1*['f'] + 1*['c'] + 1*['o']",
                                    'clf3': " -['clf3'] + 1*['cl'] + 3*['f']",
                                    'clf5': " -['clf5'] + 1*['cl'] + 5*['f']",
                                    'clf': " -['clf'] + 1*['cl'] + 1*['f']",
                                    'clno': " -['clno'] + 1*['cl'] + 1*['n'] + 1*['o']",
                                    'clo3': " -['clo3'] + 1*['cl'] + 3*['o']",
                                    'clo': " -['clo'] + 1*['cl'] + 1*['o']",
                                    'cloocl': " -['cloocl'] + 2*['cl'] + 2*['o']",
                                    'cloo': " -['cloo'] + 1*['cl'] + 2*['o']",
                                    'c-n2h2': " -['c-n2h2'] + 2*['h'] + 2*['n']",
                                    'cn': " -['cn'] + 1*['n'] + 1*['c']",
                                    'co2': " -['co2'] + 1*['c'] + 2*['o']",
                                    'co': " -['co'] + 1*['c'] + 1*['o']",
                                    'cs2': " -['cs2'] + 2*['s'] + 1*['c']",
                                    'cs': " -['cs'] + 1*['s'] + 1*['c']",
                                    'cyclobutadiene': " -['cyclobutadiene'] + 4*['h'] + 4*['c']",
                                    'cyclobutane': " -['cyclobutane'] + 8*['h'] + 4*['c']",
                                    'cyclobutene': " -['cyclobutene'] + 6*['h'] + 4*['c']",
                                    'cyclopentadiene': " -['cyclopentadiene'] + 6*['h'] + 5*['c']",
                                    'cyclopropane': " -['cyclopropane'] + 6*['h'] + 3*['c']",
                                    'cyclopropene': " -['cyclopropene'] + 4*['h'] + 3*['c']",
                                    'cyclopropyl': " -['cyclopropyl'] + 5*['h'] + 3*['c']",
                                    'dioxetan2one': " -['dioxetan2one'] + 2*['h'] + 2*['c'] + 3*['o']",
                                    'dioxetane': " -['dioxetane'] + 4*['h'] + 2*['c'] + 2*['o']",
                                    'dioxirane': " -['dioxirane'] + 2*['h'] + 1*['c'] + 2*['o']",
                                    'dithiotane': " -['dithiotane'] + 2*['s'] + 4*['h'] + 2*['c']",
                                    'ethanol': " -['ethanol'] + 6*['h'] + 2*['c'] + 1*['o']",
                                    'f2co': " -['f2co'] + 2*['f'] + 1*['c'] + 1*['o']",
                                    'f2': " -['f2'] + 2*['f']",
                                    'f2o': " -['f2o'] + 2*['f'] + 1*['o']",
                                    'fccf': " -['fccf'] + 2*['f'] + 2*['c']",
                                    'fno': " -['fno'] + 1*['f'] + 1*['n'] + 1*['o']",
                                    'fo2': " -['fo2'] + 1*['f'] + 2*['o']",
                                    'foof': " -['foof'] + 2*['f'] + 2*['o']",
                                    'formamide': " -['formamide'] + 1*['n'] + 3*['h'] + 1*['c'] + 1*['o']",
                                    'formic-anhydride': " -['formic-anhydride'] + 2*['h'] + 2*['c'] + 3*['o']",
                                    'formic': " -['formic'] + 2*['h'] + 1*['c'] + 2*['o']",
                                    'furan': " -['furan'] + 4*['h'] + 4*['c'] + 1*['o']",
                                    'glyoxal': " -['glyoxal'] + 2*['h'] + 2*['c'] + 2*['o']",
                                    'h2ccn': " -['h2ccn'] + 1*['n'] + 2*['h'] + 2*['c']",
                                    'h2cn': " -['h2cn'] + 1*['n'] + 2*['h'] + 1*['c']",
                                    'h2co': " -['h2co'] + 2*['h'] + 1*['c'] + 1*['o']",
                                    'h2': " -['h2'] + 2*['h']",
                                    'h2no': " -['h2no'] + 2*['h'] + 1*['n'] + 1*['o']",
                                    'h2o': " -['h2o'] + 2*['h'] + 1*['o']",
                                    'h2s': " -['h2s'] + 2*['h'] + 1*['s']",
                                    'hccf': " -['hccf'] + 1*['f'] + 1*['h'] + 2*['c']",
                                    'hcl': " -['hcl'] + 1*['cl'] + 1*['h']",
                                    'hclo4': " -['hclo4'] + 1*['cl'] + 1*['h'] + 4*['o']",
                                    'hcn': " -['hcn'] + 1*['n'] + 1*['h'] + 1*['c']",
                                    'hcnh': " -['hcnh'] + 1*['n'] + 2*['h'] + 1*['c']",
                                    'hcno': " -['hcno'] + 1*['n'] + 1*['h'] + 1*['c'] + 1*['o']",
                                    'hco': " -['hco'] + 1*['h'] + 1*['c'] + 1*['o']",
                                    'hcof': " -['hcof'] + 1*['f'] + 1*['h'] + 1*['c'] + 1*['o']",
                                    'hf': " -['hf'] + 1*['h'] + 1*['f']",
                                    'hnc': " -['hnc'] + 1*['c'] + 1*['h'] + 1*['n']",
                                    'hnco': " -['hnco'] + 1*['h'] + 1*['n'] + 1*['c'] + 1*['o']",
                                    'hnnn': " -['hnnn'] + 1*['h'] + 3*['n']",
                                    'hno': " -['hno'] + 1*['h'] + 1*['n'] + 1*['o']",
                                    'hocl': " -['hocl'] + 1*['cl'] + 1*['h'] + 1*['o']",
                                    'hocn': " -['hocn'] + 1*['h'] + 1*['n'] + 1*['c'] + 1*['o']",
                                    'hoclo': " -['hoclo'] + 1*['cl'] + 1*['h'] + 2*['o']",
                                    'hof': " -['hof'] + 1*['f'] + 1*['h'] + 1*['o']",
                                    'honc': " -['honc'] + 1*['c'] + 1*['h'] + 1*['n'] + 1*['o']",
                                    'hoo': " -['hoo'] + 1*['h'] + 2*['o']",
                                    'hooh': " -['hooh'] + 2*['h'] + 2*['o']",
                                    'hs': " -['hs'] + 1*['h'] + 1*['s']",
                                    'ketene': " -['ketene'] + 2*['h'] + 2*['c'] + 1*['o']",
                                    'methanol': " -['methanol'] + 4*['h'] + 1*['c'] + 1*['o']",
                                    'n2': " -['n2'] + 2*['n']",
                                    'n2h4': " -['n2h4'] + 4*['h'] + 2*['n']",
                                    'n2h': " -['n2h'] + 1*['h'] + 2*['n']",
                                    'n2o4': " -['n2o4'] + 2*['n'] + 4*['o']",
                                    'n2o': " -['n2o'] + 2*['n'] + 1*['o']",
                                    'n-butane': " -['n-butane'] + 10*['h'] + 4*['c']",
                                    'nccn': " -['nccn'] + 2*['n'] + 2*['c']",
                                    'nh2cl': " -['nh2cl'] + 2*['h'] + 1*['cl'] + 1*['n']",
                                    'nh2': " -['nh2'] + 2*['h'] + 1*['n']",
                                    'nh2f': " -['nh2f'] + 2*['h'] + 1*['n'] + 1*['f']",
                                    'nh2oh': " -['nh2oh'] + 3*['h'] + 1*['n'] + 1*['o']",
                                    'nh3': " -['nh3'] + 3*['h'] + 1*['n']",
                                    'nh': " -['nh'] + 1*['h'] + 1*['n']",
                                    'no2': " -['no2'] + 1*['n'] + 2*['o']",
                                    'no': " -['no'] + 1*['n'] + 1*['o']",
                                    'n-pentane': " -['n-pentane'] + 12*['h'] + 5*['c']",
                                    'o2': " -['o2'] + 2*['o']",
                                    'o3': " -['o3'] + 3*['o']",
                                    'oclo': " -['oclo'] + 1*['cl'] + 2*['o']",
                                    'ocs': " -['ocs'] + 1*['s'] + 1*['c'] + 1*['o']",
                                    'of': " -['of'] + 1*['f'] + 1*['o']",
                                    'oh': " -['oh'] + 1*['h'] + 1*['o']",
                                    'oxadiazole': " -['oxadiazole'] + 2*['n'] + 2*['h'] + 2*['c'] + 1*['o']",
                                    'oxetane': " -['oxetane'] + 6*['h'] + 3*['c'] + 1*['o']",
                                    'oxirane': " -['oxirane'] + 4*['h'] + 2*['c'] + 1*['o']",
                                    'oxirene': " -['oxirene'] + 2*['h'] + 2*['c'] + 1*['o']",
                                    'p2': " -['p2'] + 2*['p']",
                                    'p4': " -['p4'] + 4*['p']",
                                    'pf3': " -['pf3'] + 3*['f'] + 1*['p']",
                                    'pf5': " -['pf5'] + 5*['f'] + 1*['p']",
                                    'ph3': " -['ph3'] + 3*['h'] + 1*['p']",
                                    'propane': " -['propane'] + 8*['h'] + 3*['c']",
                                    'propene': " -['propene'] + 6*['h'] + 3*['c']",
                                    'propyne': " -['propyne'] + 4*['h'] + 3*['c']",
                                    'pyrrole': " -['pyrrole'] + 5*['h'] + 1*['n'] + 4*['c']",
                                    's2': " -['s2'] + 2*['s']",
                                    's2o': " -['s2o'] + 2*['s'] + 1*['o']",
                                    's3': " -['s3'] + 3*['s']",
                                    's4-c2v': " -['s4-c2v'] + 4*['s']",
                                    'sf6': " -['sf6'] + 6*['f'] + 1*['s']",
                                    'si2h6': " -['si2h6'] + 6*['h'] + 2*['si']",
                                    'sif4': " -['sif4'] + 4*['f'] + 1*['si']",
                                    'sif': " -['sif'] + 1*['f'] + 1*['si']",
                                    'sih3f': " -['sih3f'] + 3*['h'] + 1*['f'] + 1*['si']",
                                    'sih4': " -['sih4'] + 4*['h'] + 1*['si']",
                                    'sih': " -['sih'] + 1*['h'] + 1*['si']",
                                    'silole': " -['silole'] + 6*['h'] + 4*['c'] + 1*['si']",
                                    'sio': " -['sio'] + 1*['o'] + 1*['si']",
                                    'so2': " -['so2'] + 1*['s'] + 2*['o']",
                                    'so3': " -['so3'] + 1*['s'] + 3*['o']",
                                    'so': " -['so'] + 1*['s'] + 1*['o']",
                                    'ssh': " -['ssh'] + 1*['h'] + 2*['s']",
                                    't-butadiene': " -['t-butadiene'] + 6*['h'] + 4*['c']",
                                    'tetrahedrane': " -['tetrahedrane'] + 4*['h'] + 4*['c']",
                                    't-hcoh': " -['t-hcoh'] + 2*['h'] + 1*['c'] + 1*['o']",
                                    'thiophene': " -['thiophene'] + 1*['s'] + 4*['h'] + 4*['c']",
                                    't-hono': " -['t-hono'] + 1*['h'] + 1*['n'] + 2*['o']",
                                    't-hooo': " -['t-hooo'] + 1*['h'] + 3*['o']",
                                    't-n2h2': " -['t-n2h2'] + 2*['h'] + 2*['n']",
                                    'trans-c2f2cl2': " -['trans-c2f2cl2'] + 2*['cl'] + 2*['f'] + 2*['c']",
    
        }
 
        self.charges = { "acetaldehyde": -0.000,
                         "acetic": -0.000,
                         "al": -0.000,
                         "alcl": 0.000,
                         "alcl3": -0.000,
                         "alf": -0.000,
                         "alf3": -0.000,
                         "alh": -0.000,
                         "alh3": -0.000,
                         "allene": 0.000,
                         "allyl": 0.000,
                         "b": -0.000,
                         "b2": 0.000,
                         "b2h6": 0.000,
                         "benzene": 0.000,
                         "beta-lactim": 0.000,
                         "bf": 0.000,
                         "bf3": 0.000,
                         "bh": -0.000,
                         "bh3": -0.000,
                         "bhf2": -0.000,
                         "bn": 0.000,
                         "bn3pi": 0.000,
                         "borole": 0.000,
                         "c": -0.000,
                         "c2": 0.000,
                         "c2cl2": 0.000,
                         "c2cl4": 0.000,
                         "c2cl6": 0.000,
                         "c2clh": 0.000,
                         "c2clh3": -0.000,
                         "c2clh5": -0.000,
                         "c2f4": -0.000,
                         "c2f6": -0.000,
                         "c2h2": 0.000,
                         "c2h3f": 0.000,
                         "c2h4": 0.000,
                         "c2h5f": 0.000,
                         "c2h6": 0.000,
                         "cch": -0.000,
                         "ccl2": -0.000,
                         "ccl2h2": -0.000,
                         "ccl2o": 0.000,
                         "ccl3h": 0.000,
                         "ccl4": 0.000,
                         "cclh3": -0.000,
                         "cf": 0.000,
                         "cf2": 0.000,
                         "cf2cl2": 0.000,
                         "cf4": -0.000,
                         "ch": -0.000,
                         "ch2c": 0.000,
                         "ch2ch": 0.000,
                         "ch2clf": -0.000,
                         "ch2f2": -0.000,
                         "ch2nh": 0.000,
                         "ch2nh2": -0.000,
                         "ch2-sing": 0.000,
                         "ch2-trip": 0.000,
                         "ch3": 0.000,
                         "ch3f": 0.000,
                         "ch3nh": 0.000,
                         "ch3nh2": -0.000,
                         "ch3ph2": -0.000,
                         "ch4": -0.000,
                         "c-hcoh": 0.000,
                         "chf3": -0.000,
                         "c-hono": -0.000,
                         "c-hooo": 0.000,
                         "cis-c2f2cl2": 0.000,
                         "cl": -0.000,
                         "cl2": -0.000,
                         "cl2o": 0.000,
                         "clcn": 0.000,
                         "clcof": 0.000,
                         "clf": -0.000,
                         "clf3": 0.000,
                         "clf5": -0.000,
                         "clno": 0.000,
                         "clo": -0.000,
                         "clo3": -0.000,
                         "cloo": -0.000,
                         "cloocl": -0.000,
                         "cn": 0.000,
                         "c-n2h2": 0.000,
                         "co": -0.000,
                         "co2": -0.000,
                         "cs": -0.000,
                         "cs2": 0.000,
                         "cyclobutadiene": 0.000,
                         "cyclobutane": 0.000,
                         "cyclobutene": 0.000,
                         "cyclopentadiene": -0.000,
                         "cyclopropane": 0.000,
                         "cyclopropene": 0.000,
                         "cyclopropyl": 0.000,
                         "dioxetan2one": 0.000,
                         "dioxetane": 0.000,
                         "dioxirane": -0.000,
                         "dithiotane": -0.000,
                         "ethanol": -0.000,
                         "f": -0.000,
                         "f2": 0.000,
                         "f2co": -0.000,
                         "f2o": -0.000,
                         "fccf": -0.000,
                         "fno": -0.000,
                         "fo2": -0.000,
                         "foof": 0.000,
                         "formamide": -0.000,
                         "formic": -0.000,
                         "formic-anhydride": -0.000,
                         "furan": -0.000,
                         "glyoxal": 0.000,
                         "h": -0.000,
                         "h2": 0.000,
                         "h2ccn": 0.000,
                         "h2cn": 0.000,
                         "h2co": 0.000,
                         "h2no": 0.000,
                         "h2o": 0.000,
                         "h2s": -0.000,
                         "hccf": -0.000,
                         "hcl": -0.000,
                         "hclo4": -0.000,
                         "hcn": -0.000,
                         "hcnh": 0.000,
                         "hcno": -0.000,
                         "hco": 0.000,
                         "hcof": 0.000,
                         "hf": -0.000,
                         "hnc": 0.000,
                         "hnco": -0.000,
                         "hnnn": -0.000,
                         "hno": 0.000,
                         "hocl": 0.000,
                         "hoclo": -0.000,
                         "hoclo2": 0.000,
                         "hocn": -0.000,
                         "hof": -0.000,
                         "honc": -0.000,
                         "hoo": 0.000,
                         "hooh": -0.000,
                         "hs": -0.000,
                         "ketene": -0.000,
                         "methanol": 0.000,
                         "n": -0.000,
                         "n2": 0.000,
                         "n2h": 0.000,
                         "n2h4": 0.000,
                         "n2o": -0.000,
                         "n2o4": 0.000,
                         "n-butane": 0.000,
                         "nccn": 0.000,
                         "nh": 0.000,
                         "nh2": -0.000,
                         "nh2cl": 0.000,
                         "nh2f": 0.000,
                         "nh2oh": 0.000,
                         "nh3": -0.000,
                         "no": 0.000,
                         "no2": -0.000,
                         "n-pentane": -0.000,
                         "o": -0.000,
                         "o2": 0.000,
                         "o3": -0.000,
                         "oclo": -0.000,
                         "ocs": -0.000,
                         "of": -0.000,
                         "oh": 0.000,
                         "oxadiazole": -0.000,
                         "oxetane": 0.000,
                         "oxirane": 0.000,
                         "oxirene": 0.000,
                         "p": -0.000,
                         "p2": -0.000,
                         "p4": -0.000,
                         "pf3": -0.000,
                         "pf5": -0.000,
                         "ph3": -0.000,
                         "propane": 0.000,
                         "propene": 0.000,
                         "propyne": -0.000,
                         "pyrrole": -0.000,
                         "s": -0.000,
                         "s2": 0.000,
                         "s2o": 0.000,
                         "s3": -0.000,
                         "s4-c2v": -0.000,
                         "sf6": -0.000,
                         "si": -0.000,
                         "si2h6": -0.000,
                         "sif": -0.000,
                         "sif4": 0.000,
                         "sih": -0.000,
                         "sih3f": 0.000,
                         "sih4": 0.000,
                         "silole": 0.000,
                         "sio": -0.000,
                         "so": 0.000,
                         "so2": -0.000,
                         "so3": -0.000,
                         "ssh": -0.000,
                         "t-butadiene": 0.000,
                         "tetrahedrane": 0.000,
                         "t-hcoh": 0.000,
                         "thiophene": -0.000,
                         "t-hono": 0.000,
                         "t-hooo": 0.000,
                         "t-n2h2": 0.000,
                         "trans-c2f2cl2": 0.000}
